#
# NetOffice Samples repository
# AppVeyor configuration
#

version: 1.7.4.{build}

branches:
  except:
    - gh-pages
    - import/*

os: Visual Studio 2015

platform: Any CPU
configuration:
  - Debug
  - Release

build_script:
  - ps: .\build.ps1 -Verbosity Normal

assembly_info:
  patch: true
  file: 'AssemblyInfo.cs'
  assembly_version: "{version}"
  assembly_file_version: "{version}"
  assembly_informational_version: "1.7.4-alpha-{build}"

test: off

cache:
  - packages -> **\packages.config
  - tools -> tools\packages.config
